<?php


namespace Test;


use App\Coverage;
use PHPUnit\Framework\TestCase;

class CoverageTest extends TestCase
{
    /**
     * @var null | Coverage
     */
    public $coverage = null;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->coverage = new Coverage();
    }

    public function testCoverage()
    {
        $this->assertIsInt($this->coverage->add());
        $this->assertIsInt($this->coverage->div());
        $this->assertIsInt($this->coverage->mul());
        $this->assertIsInt($this->coverage->sub());
        $array = [
            1, 2, 3, 4, 5, 6, 7, 8, 9, 10
        ];
        $find = 2;
        $this->assertIsBool($this->coverage->find($array, $find));
    }
}
